### 把sparse tensor转为邻接矩阵

In [2]:
from torch_sparse import SparseTensor
import torch
# 创建一个稀疏矩阵
row_indices = torch.tensor([0, 1, 1, 2])
print(row_indices)
col_indices = torch.tensor([1, 0, 2, 1])
print(col_indices)
values = torch.tensor([1, 2, 3, 4])
sparse_tensor = SparseTensor(row=row_indices, col=col_indices, value=values)
# SparseTensor( row=tensor([0, 1, 1, 2]),
#               col=tensor([1, 0, 2, 1]),
#               val=tensor([1, 2, 3, 4]),
#               size=(3, 3), nnz=4, density=44.44%)
print(sparse_tensor)
densor_tensor = sparse_tensor.to_dense()
# tensor([[0, 1, 0],
#         [2, 0, 3],
#         [0, 4, 0]])
print(densor_tensor)
# 将稀疏矩阵转换为CSR格式
csr_tensor = sparse_tensor.csr()
# (tensor([0, 1, 3, 4]), tensor([1, 0, 2, 1]), tensor([1, 2, 3, 4]))
# 对于CSR格式，包括三个list, 分别是
# 行偏移数组（row offsets):     tensor([0, 1, 3, 4]) 
#           该数组是一个二位数组中每行第一个非0元素在values数组的index。
#           大小为（行数+1）
# 列索引数组（column indices):  tensor([1, 0, 2, 1]) 
#           该数组是values数组中每一个元素的列
#           大小为values数组的大小
# 值数组（values)               tensor([1, 2, 3, 4])

print(csr_tensor)

tensor([0, 1, 1, 2])
tensor([1, 0, 2, 1])
SparseTensor(row=tensor([0, 1, 1, 2]),
             col=tensor([1, 0, 2, 1]),
             val=tensor([1, 2, 3, 4]),
             size=(3, 3), nnz=4, density=44.44%)
tensor([[0, 1, 0],
        [2, 0, 3],
        [0, 4, 0]])
(tensor([0, 1, 3, 4]), tensor([1, 0, 2, 1]), tensor([1, 2, 3, 4]))
